version: '3'
services:
    app:
        build: .
        image: duchometson/challenger-bravo:0.1
        ports:
            - 5000:5000
        environment:
            PORT: 5000
            FLASK_DEBUG: 1

